### ISSUE TITLE
taskbar not reapperaing

### ISSUE THREAD

**Issue by drCurse** [ongots/pseudo-fullscreen-firefox#5]
My hidden taskbar does not reappear only while using firefox i love this css but this issue is bugging me! plz Help!!

**Comment by ongots** [comment]
Возможно вы вошли в полноэкранный режим браузера, выйдите из него нажав F11.

Иногда если панель задач не появляется достаточно нажать WIN. Если не помогает перезапустите проводник через диспетчер задач. 

Еще у меня есть скрипт позволяющий закреплять окно поверх остальных, оно также скрывает панель задач. Но такой скрипт мало кто использует.
