### ISSUE TITLE
want the nav bar to be on the bottom  and auto hide

### ISSUE THREAD

**Issue by drCurse** [ongots/pseudo-fullscreen-firefox#6]
hello, i am using a gnome setup with a top bar i want the nav bar to be on the bottom how do i do it.

**Comment by ongots** [comment]
If I were you, I would install [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/)

But if you really want to, add this to the end of userChrome.css:
```
.global-notificationbox,
#mainPopupSet,
#browser,
#customization-container,
#tab-notification-deck {
  order: -1}

[sizemode=maximized] #nav-bar:not([customizing]):not(:has([tab-notification-box-0])) {margin-bottom: -36px; top: 0px}

#nav-bar:is(:hover, :focus-within, :has(*[open]), :has(*[dragstart])) {top: -36px !important}
```
This is a code modification from the Firefox-beta branch that will be released with Firefox 133
Next on your own

**Comment by drCurse** [comment]
i tried the code now i don't have a nav bar neither on top or bottom

**Comment by ongots** [comment]
Auto-hide was broken in Firefox 133 beta, I fixed it in the "Firefox-beta" branch. Wait for Firefox 133, update 
pseudo-fullscreen-firefox, add a modification down, change the values ​​in px (hidden margins may differ on different systems), you will also need to select the margins for [sizemode=normal].
I currently only have a system with Win10, Firefox beta. I can't test the code on GNOME and won't support it.

With [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) everything should work without modifications, I assume.

**Comment by drCurse** [comment]
in the new css this does not work anymore help i tried using chat gpt but it did not work

**Comment by ongots** [comment]
What exactly is not working? I've tested the navbar, and the menus are working, but the urlbar doesn't open.

**Comment by drCurse** [comment]
there is a floating search widget on the top sometimes and the navbar is not hiding its as shown in the video.
I use floorp because it allows to put the url bar on the bottom so that i can see the search suggestions + privacy. 
on older floorp version  your userChrome.css + the above code worked flawlessly.


https://github.com/user-attachments/assets/fb72fbc5-5148-424b-a867-42ea398f4508

**Comment by ongots** [comment]
Floorp is based on Firefox 122. Try the userChrome.css from that period:
https://github.com/ongots/pseudo-fullscreen-firefox/blob/8213816d97c50b5cec18afd0876949ebd065552e/chrome/userChrome.css

I do not support outdated versions of Firefox, and I remove code that goes beyond the release version.

I tested the Firefox 145beta win10 panel navigation opens correctly (does not jump in height)

**Comment by drCurse** [comment]
i switched to firefox i have this floating window when i open any website and search suggestions do not 

https://github.com/user-attachments/assets/7a848b5e-ff29-4731-897a-7beb46bf16b7

show

**Comment by ongots** [comment]
I don't have any problems like that.
Try https://github.com/FineFuturity/FrameUIForFirefox/
Or you have to fix it yourself through the Browser Toolbox
https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/
